<tsd:PluginWindowBase x:Class="CreatePartMarkForSlab.MainWindow"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        xmlns:UIControls="clr-namespace:Tekla.Structures.Dialog.UIControls;assembly=Tekla.Structures.Dialog"
        xmlns:tsd="clr-namespace:Tekla.Structures.Dialog;assembly=Tekla.Structures.Dialog"
        xmlns:local="clr-namespace:CreatePartMarkForSlab"
        mc:Ignorable="d"
        Title="Slab Mark Symbol" 
        ResizeMode="NoResize"
        Height="300"
        Width="600"
        MaxHeight="300" 
        MaxWidth="600">
    <d:UserControl.DataContext>
        <local:MainWindowViewModel/>
    </d:UserControl.DataContext>
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition Height="Auto" MinHeight="48" />
            <RowDefinition />
            <RowDefinition Height="Auto" MinHeight="48" />
        </Grid.RowDefinitions>
        <UIControls:WpfSaveLoad
            AttributesSaveClicked="WpfSaveLoad_AttributesSaveClicked"
            Grid.Row="0"
            Margin="0,0,0,0"
            HorizontalAlignment="Stretch"
            VerticalAlignment="Top" />
        <StackPanel Name="MainContent" 
              Grid.Row="1"
              Margin="10, 0, 10, 0">
            <GroupBox 
                Header="Setting Slab Mark"
                Grid.Column="0">
                <Grid>
                    <Grid.RowDefinitions>
                        <RowDefinition/>
                        <RowDefinition/>
                        <RowDefinition/>
                        <RowDefinition/>
                        <RowDefinition/>
                    </Grid.RowDefinitions>
                    <Grid.ColumnDefinitions>
                        <ColumnDefinition/>
                        <ColumnDefinition/>
                    </Grid.ColumnDefinitions>
                    <StackPanel 
                        Grid.Row="0" 
                        Orientation="Horizontal">
                        <Grid>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition/>
                                <ColumnDefinition/>
                            </Grid.ColumnDefinitions>
                            <Label
                                Grid.Column="0"
                                Width="100"
                                HorizontalAlignment="Left"
                                VerticalAlignment="Center"
                                Content="Mark Type"/>
                            <StackPanel 
                                Grid.Column="1" 
                                VerticalAlignment="Center" 
                                Orientation="Horizontal">
                                <UIControls:WpfFilterCheckBox
                                    HorizontalAlignment="Left"
                                    VerticalAlignment="Center"
                                    AttributeName="slabmarktype" />
                                <ComboBox
                                    x:Name="slabmarktype"
                                    Width="120"
                                    VerticalAlignment="Center"
                                    ItemsSource="{Binding Slabmarktypes}"
                                    SelectedValue="{Binding Path=Slabmarktype, Mode=TwoWay}">   
                                </ComboBox>
                            </StackPanel>
                        </Grid>
                    </StackPanel>
                    <StackPanel 
                        Grid.Row="1" 
                        Orientation="Horizontal">
                        <Grid>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition/>
                                <ColumnDefinition/>
                            </Grid.ColumnDefinitions>
                            <Label
                                Grid.Column="0"
                                Width="100"
                                Height="30"
                                HorizontalAlignment="Left"
                                VerticalAlignment="Center"
                                Content="Custom Mark" />
                            <StackPanel 
                                Grid.Column="1"
                                Orientation="Horizontal">
                                <UIControls:WpfFilterCheckBox
                                    HorizontalAlignment="Left"
                                    VerticalAlignment="Center"
                                    AttributeName="slabprefix" />
                                <TextBox
                                    x:Name="slabprefix"
                                    Width="120"
                                    Height="23"
                                    HorizontalAlignment="Left"
                                    VerticalAlignment="Center"
                                    Text="{Binding Slabprefix, Mode=TwoWay}"
                                    IsEnabled="{Binding Slabprefixaction}"
                                    TextWrapping="Wrap" />
                            </StackPanel>
                        </Grid>
                    </StackPanel>
                    <StackPanel 
                        Grid.Row="0"
                        Grid.Column="1"
                        Orientation="Horizontal">
                        <Grid>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition/>
                                <ColumnDefinition/>
                            </Grid.ColumnDefinitions>
                            <Label
                                Grid.Column="0"
                                Width="100"
                                Height="30"
                                HorizontalAlignment="Left"
                                VerticalAlignment="Center"
                                Content="Mark Extend" />
                            <StackPanel 
                                Grid.Column="1"
                                Orientation="Horizontal">
                                <UIControls:WpfFilterCheckBox
                                    HorizontalAlignment="Left"
                                    VerticalAlignment="Center"
                                    AttributeName="slabextendmark" />
                                <TextBox
                                    x:Name="slabextendmark"
                                    Width="120"
                                    Height="23"
                                    HorizontalAlignment="Left"
                                    VerticalAlignment="Center"
                                    Text="{Binding Slabextendmark, Mode=TwoWay}"
                                    TextWrapping="Wrap" />
                            </StackPanel>
                        </Grid>
                    </StackPanel>
                    <StackPanel 
                        Grid.Row="1" 
                        Grid.Column="1"
                        Orientation="Horizontal">
                        <Grid>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition/>
                                <ColumnDefinition/>
                            </Grid.ColumnDefinitions>
                            <Label
                                Grid.Column="0"
                                Width="100"
                                Height="30"
                                HorizontalAlignment="Left"
                                VerticalAlignment="Center"
                                Content="Mark Angle" />
                            <StackPanel 
                                Grid.Column="1"
                                Orientation="Horizontal">
                                <UIControls:WpfFilterCheckBox
                                    HorizontalAlignment="Left"
                                    VerticalAlignment="Center"
                                    AttributeName="slabanglemark" />
                                <TextBox
                                    x:Name="slabanglemark"
                                    Width="120"
                                    Height="23"
                                    HorizontalAlignment="Left"
                                    VerticalAlignment="Center"
                                    Text="{Binding Slabanglemark, Mode=TwoWay}"
                                    TextWrapping="Wrap" />
                            </StackPanel>
                        </Grid>
                    </StackPanel>
                    <StackPanel 
                        Grid.Row="4" 
                        Orientation="Horizontal">
                        <Grid>
                            <Grid.ColumnDefinitions>
                                <ColumnDefinition/>
                                <ColumnDefinition/>
                            </Grid.ColumnDefinitions>
                            <Label
                                Grid.Column="0"
                                Width="100"
                                HorizontalAlignment="Left"
                                VerticalAlignment="Center"
                                Content="Apply For"/>
                            <StackPanel 
                                Grid.Column="1" 
                                VerticalAlignment="Center" 
                                Orientation="Horizontal">
                                <UIControls:WpfFilterCheckBox
                                    HorizontalAlignment="Left"
                                    VerticalAlignment="Center"
                                    AttributeName="isApplyFor" />
                                <ComboBox
                                    x:Name="isApplyFor"
                                    Width="120"
                                    VerticalAlignment="Center"
                                    SelectedIndex="{Binding Path=IsApplyFor, Mode=TwoWay}">
                                    <TextBlock Text="Slab selected."/>
                                    <TextBlock Text="All slabs in selected view."/>
                                </ComboBox>
                            </StackPanel>
                        </Grid>
                    </StackPanel>
                </Grid>
            </GroupBox>
        </StackPanel>
        <UIControls:WpfOkApplyModifyGetOnOffCancel
            Grid.Row="2"
            ApplyClicked="WPFOkApplyModifyGetOnOffCancel_ApplyClicked"
            CancelClicked="WPFOkApplyModifyGetOnOffCancel_CancelClicked"
            GetClicked="WPFOkApplyModifyGetOnOffCancel_GetClicked"
            ModifyClicked="WPFOkApplyModifyGetOnOffCancel_ModifyClicked"
            OkClicked="WPFOkApplyModifyGetOnOffCancel_OkClicked"
            OnOffClicked="WPFOkApplyModifyGetOnOffCancel_OnOffClicked"/>
    </Grid>
</tsd:PluginWindowBase>
